apiVersion: v1
kind: Secret
metadata:
  name: billing-app-secret
  namespace: dev  # Replace with your namespace
data:
  DJANGO_SECRET_KEY: ${{DJANGO_SECRET_KEY}}
  POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
  POSTGRES_USER: ${{POSTGRES_USER}}
  EMAIL_HOST_USER: ${{EMAIL_HOST_USER}}
  ENCRYPTED_EMAIL_PASSWORD: ${{ENCRYPTED_EMAIL_PASSWORD}}

