apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-billing
  namespace: dev
data:
  DJANGO_SUPERUSER_USERNAME: ${{DJANGO_SUPERUSER_USERNAME}}
  DJANGO_SUERPUSER_EMAIL: ${{DJANGO_SUERPUSER_EMAIL}}
  POSTGRES_ENGINE:  django.db.backends.postgresql
  POSTGRES_DB: postgres
  POSTGRES_HOST: db-service
  POSTGRES_PORT: "5432"
  ALLOWED_HOSTS: billingsystem.dev.svc.cluster.local,*.svc.cluster.local,billingsystem-service,billingsystem,20.219.243.156
  CSRF_TRUSTED_ORIGINS: http://billingsystem,http://billingsystem-service,http://proxy-service,http://20.219.243.156,https://20.219.243.156

  