apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingsystem
  namespace: billing-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billingsystem
  template:
    metadata:
      labels:
        app: billingsystem
    spec:
      hostname: billingsystem
      containers:
      - name: billingsystem
        image: monarch.azurecr.io/motorvehicle-retail-app-billingsystem:latest
        ports:
        - containerPort: 8000
        envFrom: 
          - configMapRef:
             name: env-config
        volumeMounts:
        - name: billing-data 
          mountPath: /BillingSystem
        - name: static-data
          mountPath: /vol/web
        command: ["sh", "-c", "sh /scripts/entrypoint.sh"]
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      volumes:
      - name: static-data
        persistentVolumeClaim:
          claimName: static-data-pvc
      - name: billing-data
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: billingsystem-service
  namespace: billing-system
spec:
  selector:
    app: billingsystem
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: billing-port
