# version: "3.9"
# services:
#   billingsystem:
#     depends_on:
#       - postgres_db
#     build:
#       context: ./BillingSystem
#       dockerfile: Dockerfile
#     image: billingsystem-k8s:v1
#     environment:
#       - PORT=8020
#     env_file:
#       - BillingSystem/.env
#     ports:
#       - "8001:8020"
#     command: sh -c "ls -ltr /app/"
#     volumes:
#        - staticfiles:/vol/web/
#   postgres_db:
#     image: postgres:latest
#     restart: always
#     command: -p 5434
#     env_file: 
#       - BillingSystem/.env
#     expose:
#       - 5434
#     ports:
#       - "5434:5434"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#   redis_db:
#     image: redis
#     restart: always
#     expose:
#       - 6388
#     ports:
#       - "6388:6388"
#     volumes:
#         - redis_data:/data
#     entrypoint: redis-server --appendonly yes --port 6388


# volumes:
#   # staticfiles:
#   #     external: true
#   postgres_data:
#   redis_data: 


version: '3.9'

services:
  billingsystem:
    build:
      context: ./BillingSystem
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./BillingSystem:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1