# version: '3.9'
services:
  billingsystem:
    dns:
     - 8.8.8.8
     - 8.8.4.4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billingsystem
    volumes:
      - ./BillingSystem:/BillingSystem
      - static_data:/vol/web
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "sh /scripts/entrypoint.sh"
    networks:
     - my-network

  proxy:
    dns:
     - 8.8.8.8
     - 8.8.4.4
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - billingsystem
    networks:
     - my-network

volumes:
  static_data:

networks:
  my-network:
    driver: bridge