version: '3.9'

services:
  billingsystem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_data:/vol/web
    environment:
      - PORT=8000
    ports:
      - "8000:8020"
    env_file:
      - .env
    command: sh -c "sh /scripts/migrate.sh && sh /scripts/entrypoint.sh"
    networks:
     - my-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - billingsystem
    networks:
     - my-network

volumes:
  static_data:

networks:
  my-network:
