apiVersion: v1
kind: Service
metadata:
  name: combined-service
  namespace: billing-system
spec:
  type: LoadBalancer
  selector:
    app: combined-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: billing-port
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: proxy-port