# Generated by Django 5.1 on 2024-10-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
        ('inventory', '0014_remove_product_description_product_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='email')),
                ('Contact', models.PositiveIntegerField(verbose_name='Contact Number')),
                ('Address', models.TextField(verbose_name='Address')),
                ('Identification', models.CharField(max_length=10, verbose_name='Gov ID')),
                ('ID_number', models.CharField(max_length=10, verbose_name='ID Number')),
                ('Payment_mode', models.CharField(max_length=20, verbose_name='Payment Mode')),
            ],
        ),
        migrations.CreateModel(
            name='Stockview',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
            ],
            bases=('inventory.product',),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Battery_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Chasis_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Engine_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Invoice_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Key_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Serial_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
