# Generated by Django 5.1 on 2024-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_customer_details_stockview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AddConstraint(
            model_name='customer_details',
            constraint=models.UniqueConstraint(fields=('Name', 'Email', 'Contact'), name='unique_customer'),
        ),
    ]
