# Generated by Django 5.1 on 2024-10-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_customer_details_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.PositiveIntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Sales.customer_details')),
            ],
        ),
    ]
