# Generated by Django 5.1 on 2024-10-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_customer_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_sales',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_name', to='Sales.customer_details'),
        ),
    ]
