# Generated by Django 5.1 on 2024-10-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_customer_sales_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_sales',
            name='customer_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cust_name', to='Sales.customer_details'),
        ),
        migrations.AlterField(
            model_name='customer_sales',
            name='Name',
            field=models.CharField(max_length=15),
        ),
    ]
