# Generated by Django 5.1 on 2024-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_customer_sales_customer_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='Customer_id',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='Customer_name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='Make_and_model',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='Payment_reference_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='Sales_agent',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='cust_contact',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='customer_address',
            field=models.TextField(default=None),
        ),
    ]
