# Generated by Django 5.1 on 2024-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_sales_invoice_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_sales',
            old_name='Name',
            new_name='Name_agent',
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Payment_reference_no',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
