# Generated by Django 5.1 on 2024-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_rename_name_customer_sales_name_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='Invoice_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Payment_reference_no',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Payment Reference No.'),
        ),
    ]
