# Generated by Django 5.1 on 2024-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_alter_sales_invoice_price_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='Sold_status',
            field=models.BooleanField(default=False, verbose_name='Sale status'),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='Price_break',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Price'),
        ),
    ]
