# Generated by Django 5.1 on 2024-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_alter_customer_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='Address',
            field=models.TextField(max_length=120, verbose_name='Address'),
        ),
    ]
