# Generated by Django 5.1 on 2024-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_alter_customer_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='Invoice_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Invoice ID'),
        ),
    ]
