apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: billingapp-secret-provider
  namespace: dev
spec:
  provider: azure
  parameters:
    keyvaultName: aks-k8s-keyvault
    objects: |
      array:
        - |
          objectName: "DJANGO-SECRET-KEY"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "POSTGRES-PASSWORD"
          objectType: "secret"
          objectVersion: ""
        - |    
          objectName: "POSTGRES-USER"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "EMAIL-HOST-USER"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "ENCRYPTED-EMAIL-PASSWORD"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "image-pull-secret-billingapp"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "DJANGO-SUPERUSER-USERNAME"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "DJANGO-SUPERUSER-EMAIL"
          objectType: "secret"
          objectVersion: ""
    tenantID: "aa9a00fa-e0f5-4537-a11c-9cad52d7b4a2"  
  secretObjects:
    - secretName: imagepullsecret-billingapp
      type: kubernetes.io/dockerconfigjson
      data:
        - key: ".dockerconfigjson"
          objectName: "image-pull-secret-billingapp"