apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
  namespace: dev
spec:
  provider: azure
  parameters:
    keyvaultName: aks-k8s-keyvault
    objects: |
      array:
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: POSTGRES-USER
          objectType: secret
          objectVersion: ""
    tenantID: "aa9a00fa-e0f5-4537-a11c-9cad52d7b4a2"