# Generated by Django 5.1 on 2024-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_MotorBike_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seriel_number', models.CharField(max_length=255, unique=True)),
                ('Chasis_number', models.CharField(max_length=255, unique=True)),
                ('Engine_number', models.CharField(max_length=255, unique=True)),
                ('Battery_number', models.CharField(max_length=255, unique=True)),
                ('Key_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_products_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_type', models.CharField(max_length=100)),
                ('Product_model', models.CharField(max_length=100)),
                ('Product_colour', models.CharField(max_length=100)),
                ('Product_capacity', models.IntegerField(max_length=100)),
                ('Product_price', models.IntegerField(max_length=10)),
                ('Product_count', models.IntegerField(max_length=10)),
            ],
        ),
    ]
