# Generated by Django 5.1 on 2024-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_products_type',
            name='Product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
