# Generated by Django 5.1 on 2024-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_products_type_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_products_type',
            name='Product_colour',
        ),
        migrations.AddField(
            model_name='stock_products_type',
            name='Product_status',
            field=models.BooleanField(default=True),
        ),
    ]
