# Generated by Django 5.1 on 2024-10-08 10:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stock_products_type_product_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_colour', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_model', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock_products_type',
            name='Product_capacity',
        ),
        migrations.RemoveField(
            model_name='stock_products_type',
            name='Product_model',
        ),
        migrations.AddField(
            model_name='product_motorbike_list',
            name='Engine_capacity',
            field=models.PositiveIntegerField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_motorbike_list',
            name='Product_price',
            field=models.PositiveIntegerField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_motorbike_list',
            name='year_of_make',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='stock_products_type',
            name='Product_count',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_products_type',
            name='Product_price',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AddField(
            model_name='product_motorbike_list',
            name='Product_colour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.product_colour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_motorbike_list',
            name='Product_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product_model'),
            preserve_default=False,
        ),
    ]
