# Generated by Django 5.1 on 2024-10-09 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_colour_product_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_colour', models.CharField(default=None, max_length=255)),
                ('Colour_price', models.PositiveIntegerField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_model', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_motorbike_list',
            name='Product_colour',
        ),
        migrations.RenameField(
            model_name='stock_products_type',
            old_name='Product_price',
            new_name='Product_base_price',
        ),
        migrations.AlterField(
            model_name='product_motorbike_list',
            name='Engine_capacity',
            field=models.PositiveIntegerField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='product_motorbike_list',
            name='Product_price',
            field=models.PositiveIntegerField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='product_motorbike_list',
            name='Colour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.colour_option'),
        ),
        migrations.AlterField(
            model_name='product_motorbike_list',
            name='Product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product_models'),
        ),
        migrations.DeleteModel(
            name='Product_colour',
        ),
        migrations.DeleteModel(
            name='Product_model',
        ),
    ]
