# Generated by Django 5.1 on 2024-10-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_colour_option_product_models_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_motorbike_list',
            name='Engine_capacity',
        ),
    ]
