# Generated by Django 5.1 on 2024-10-09 07:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_motorbike_list_engine_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_of_make', models.DateField(default=datetime.date.today)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('capacity', models.CharField(max_length=100)),
                ('engine_number', models.CharField(max_length=100, unique=True)),
                ('battery_number', models.CharField(max_length=100, unique=True)),
                ('key_number', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_motorbike_list',
            name='Colour',
        ),
        migrations.RemoveField(
            model_name='product_motorbike_list',
            name='Product_model',
        ),
        migrations.DeleteModel(
            name='Stock_products_type',
        ),
        migrations.AddField(
            model_name='productcolour',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='inventory.productmodel'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product_colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.productcolour'),
        ),
        migrations.DeleteModel(
            name='Colour_option',
        ),
        migrations.DeleteModel(
            name='Product_models',
        ),
        migrations.DeleteModel(
            name='Product_MotorBike_list',
        ),
    ]
