# Generated by Django 5.1 on 2024-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='model_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
