# Generated by Django 5.1 on 2024-09-26 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.CharField(max_length=255, unique=True)),
                ('Serial_number', models.CharField(max_length=255, unique=True)),
                ('Chasis_number', models.CharField(max_length=255, unique=True)),
                ('Engine_number', models.CharField(max_length=255, unique=True)),
                ('Battery_number', models.CharField(max_length=255, unique=True)),
                ('Key_number', models.CharField(max_length=255, unique=True)),
                ('Date_of_sale', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
