name: Build Image and Push

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        # Log in to Docker Hub
        echo "${{ secrets.DOCKER_SECRET }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        # Build Docker images using docker-compose
        docker compose --file docker-compose-deploy.yaml build

        # Tag and push billing image
        container_name=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -i billing)
        docker tag $container_name ${{ secrets.DOCKER_USERNAME }}/billingsystem:v1
        docker push ${{ secrets.DOCKER_USERNAME }}/billingsystem:v1

        # Tag and push proxy image
        container_name=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -i proxy)
        docker tag $container_name "${{ secrets.DOCKER_USERNAME }}/proxy:v1"
        docker push ${{ secrets.DOCKER_USERNAME }}/proxy:v1