name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: actions/checkout@v4    
    - name: Run Tests
      uses: docker/setup-docker-action@v4
    - run: |
        set -x
        docker version
        docker compose -f docker-compose-deploy.yaml up --build -d
        docker exec -i $(docker ps --format {{.Names}} | grep -i proxy) netstat -tua
        docker exec -i $(docker ps --format {{.Names}} | grep -i billingsystem) netstat -tua
        docker compose -f docker-compose-deploy.yaml down