name: Build Image and Push

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build_image_input:
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        # echo secret | docker login -u username --password-stdin azure_acr_repo.azurecr.io
        echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker compose --file docker-compose-deploy.yaml up --build -d
        container_name=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -i billing)
        # docker tag $container_name azure_acr_repo.azurecr.io/$container_name
        docker tag $container_name ${{ secrets.DOCKER_USERNAME }}/billingsystem:v1
        # docker push azure_acr_repo.azurecr.io/$container_name
        docker push ${{ secrets.DOCKER_USERNAME }}/billingsystem:v1
        container_name=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -i proxy)
        # docker tag $container_name azure_acr_repo.azurecr.io/$container_name
        docker tag $container_name ${{ secrets.DOCKER_USERNAME }}/proxy:v1
        docker push ${{ secrets.DOCKER_USERNAME }}/proxy:v1