name: CD - Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4

    - name: Set Context for Kubernetes
      uses: Azure/k8s-set-context@v4
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Check for ConfigMap and required secrets
      run: |
        if ! kubectl -n dev get cm configmap-billing; then
            kubectl -n dev -f apply menifest/app/cm-billing-app.yaml
        fi
        if ! kubectl -n dev get cm db-cm; then
            kubectl -n dev -f apply menifest/proxy/proxy_cm.yaml
        fi
        if ! kubectl -n dev get secret billing-app-secret; then
            kubectl -n dev -f apply menifest/app/billing-app-secret.yaml
        fi
        if ! kubectl -n dev get secret db-secret; then
            kubectl -n dev apply -f menifest/db/db_secret.yaml
        fi
        
    - name: Deploy DB
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: | 
          menifest/db/db.yaml 
        namespace: dev

    - name: Deploy Billing App
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: |
          menifest/app/billing-app.yaml
        namespace: dev
        
    - name: Deploy Proxy
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: |
          menifest/proxy/proxy.yaml
        namespace: dev
          
    - name: Verify Deployment 
      run: | 
        kubectl rollout status deployment/billingsystem -n dev
        kubectl rollout status deployment/proxy -n dev
