name: CD - Deploy all

on:
  workflow_dispatch:
  workflow_call:


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4

    - name: Set Context for Kubernetes
      uses: Azure/k8s-set-context@v4
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
        
        
    # - name: Encode Secrets in Base64
    #   run: |
    #     echo "DJANGO_SECRET_KEY=$(echo -n '${{ secrets.DJANGO_SECRET_KEY }}' | base64)" >> $GITHUB_ENV
    #     echo "POSTGRES_PASSWORD=$(echo -n '${{ secrets.POSTGRES_PASSWORD }}' | base64)" >> $GITHUB_ENV
    #     echo "EMAIL_HOST_USER=$(echo -n '${{ secrets.EMAIL_HOST_USER }}' | base64)" >> $GITHUB_ENV
    #     echo "ENCRYPTED_EMAIL_PASSWORD=$(echo -n '${{ secrets.ENCRYPTED_EMAIL_PASSWORD }}' | base64)" >> $GITHUB_ENV
    #     echo "DJANGO_SUPERUSER_USERNAME=$(echo -n '${{ secrets.DJANGO_SUPERUSER_USERNAME }}' | base64)" >> $GITHUB_ENV
    #     echo "DJANGO_SUERPUSER_EMAIL=$(echo -n '${{ secrets.DJANGO_SUERPUSER_EMAIL }}' | base64)" >> $GITHUB_ENV
      
    # - name: Create configMap for billing-app
    #   env:
    #     DJANGO_SUPERUSER_USERNAME: ${{ env.DJANGO_SUPERUSER_USERNAME }}
    #     DJANGO_SUERPUSER_EMAIL: ${{ env.DJANGO_SUERPUSER_EMAIL }}
    #   run: |
    #     echo "$DJANGO_SUPERUSER_USERNAME"
    #     kubectl -n dev apply -f menifest/app/cm-billing-app.yaml

    # - name: Create configMap for proxy
    #   run: |
    #       kubectl -n dev apply -f menifest/proxy/proxy_cm.yaml
          
    # - name: Create secret for billing-app
    #   env:
    #     DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
    #     POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD}}
    #     POSTGRES_USER: ${{ env.POSTGRES_USER }}
    #     EMAIL_HOST_USER: ${{ env.EMAIL_HOST_USER }}
    #     ENCRYPTED_EMAIL_PASSWORD: ${{ env.ENCRYPTED_EMAIL_PASSWORD }}
    #   run: |
    #     kubectl -n dev apply -f menifest/app/billing-app-secret.yaml

    # - name: Create secret for db
    #   env:
    #     POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    #     POSTGRES_USER: 'postgres'
    #   run: |
    #     kubectl -n dev apply -f menifest/db/db_secret.yaml
        
    - name: Deploy DB
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: | 
          menifest/db/db.yaml 
        namespace: dev

    - name: Deploy Billing App
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: |
          menifest/app/billing-app.yaml
        namespace: dev
        
    - name: Deploy Proxy
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: |
          menifest/proxy/proxy.yaml
        namespace: dev
          
    - name: Verify Deployment 
      run: | 
        kubectl rollout status deployment/billingsystem -n dev
        kubectl rollout status deployment/proxy -n dev